// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	model "github.com/bezjen/shortener/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// AuditObserver is an autogenerated mock type for the AuditObserver type
type AuditObserver struct {
	mock.Mock
}

// Notify provides a mock function with given fields: event
func (_m *AuditObserver) Notify(event model.AuditEvent) error {
	ret := _m.Called(event)

	if len(ret) == 0 {
		panic("no return value specified for Notify")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.AuditEvent) error); ok {
		r0 = rf(event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAuditObserver creates a new instance of AuditObserver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuditObserver(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuditObserver {
	mock := &AuditObserver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
