// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	model "github.com/bezjen/shortener/internal/model"
	"github.com/bezjen/shortener/internal/service"
	mock "github.com/stretchr/testify/mock"
)

// AuditService is an autogenerated mock type for the AuditService type
type AuditService struct {
	mock.Mock
}

// NotifyAll provides a mock function with given fields: event
func (_m *AuditService) NotifyAll(event model.AuditEvent) {
	_m.Called(event)
}

// RegisterObserver provides a mock function with given fields: observer
func (_m *AuditService) RegisterObserver(observer service.AuditObserver) {
	_m.Called(observer)
}

// NewAuditService creates a new instance of AuditService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuditService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuditService {
	mock := &AuditService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
